engines:
 duplication:
   enabled: true
   config:
    languages:
    - javascript:
      mass_threshold: 200
ratings:
 paths:
 - app/**
 - bin/**
 - "**.js"
exclude_paths:
- node_modules/**
- tests/**